strictness: medium
test-warnings: true
doc-warnings: false

uses:
  - django

ignore-paths:
  - config/settings.py

ignore-patterns:
  - (^|/)migrations(/|$)

pep8:
  disable:
    - W602
    - W603
  enable:
    - W601
  options:
    max-line-length: 80

mccabe:
  run: true
